name: ai_agent
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - bzip2
  - ca-certificates
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - libuuid
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - annotated-types
      - anyio
      - asttokens
      - async-timeout
      - attrs
      - certifi
      - cffi
      - charset-normalizer
      - click
      - comm
      - cryptography
      - dataclasses-json
      - debugpy
      - decorator
      - dnspython
      - exceptiongroup
      - executing
      - faiss-cpu
      - faker
      - faker-commerce
      - fastapi
      - frozenlist
      - greenlet
      - h11
      - httpcore
      - httpx
      - httpx-sse
      - idna
      - ipykernel
      - ipython
      - jedi
      - joblib
      - jsonpatch
      - jsonpointer
      - jupyter-client
      - jupyter-core
      - langchain
      - langchain-community
      - langchain-core
      - langchain-experimental
      - langchain-ollama
      - langchain-text-splitters
      - langsmith
      - marshmallow
      - matplotlib-inline
      - multidict
      - mypy-extensions
      - mysql-connector-python
      - nest-asyncio
      - numpy
      - ollama
      - orjson
      - packaging
      - pandas
      - parso
      - pexpect
      - platformdirs
      - prompt-toolkit
      - propcache
      - psutil
      - ptyprocess
      - pure-eval
      - pycparser
      - pydantic
      - pydantic-core
      - pydantic-settings
      - pygments
      - pymongo
      - pymysql
      - python-dateutil
      - python-dotenv
      - pytz
      - pyyaml
      - pyzmq
      - requests
      - requests-toolbelt
      - scikit-learn
      - scipy
      - six
      - sniffio
      - sqlalchemy
      - stack-data
      - starlette
      - tabulate
      - tenacity
      - threadpoolctl
      - tornado
      - tqdm
      - traitlets
      - typing-extensions
      - typing-inspect
      - tzdata
      - urllib3
      - uvicorn
      - wcwidth
      - yarl
      - zstandard
